[package]
name = "flour"
authors = ["patataofcourse"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.136"
serde_json = "1.0.79"
serde_derive = "1.0.136"
bytestream = "0.4.0"
clap = { version = "3.1.6", features = ["derive"] }